version: '3.7'

services:
      redis:
        image: 'redis/redis-stack:latest'
        container_name: 'redis-stack'
        ports:
          - "6379:6379"
          - "8001:8001"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes