version: '3.7'

services:
      redis:
        image: 'redis:latest'
        container_name: 'test_redis'
        ports:
          - "6379:6379"
          - "8001:8001"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes