-- MySQL Script generated by MySQL Workbench
-- Sun Feb 19 04:48:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xakaton
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xakaton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xakaton` DEFAULT CHARACTER SET utf8mb3 ;
USE `xakaton` ;

-- -----------------------------------------------------
-- Table `xakaton`.`all_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`all_users` (
  `id_user` INT NOT NULL,
  `post` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`admin` (
  `id_admin` INT NOT NULL,
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `id_admin_UNIQUE` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_admin_all_users1`
    FOREIGN KEY (`id_admin`)
    REFERENCES `xakaton`.`all_users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`ban_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`ban_list` (
  `id_user` INT NOT NULL,
  `post` VARCHAR(45) NOT NULL DEFAULT 'staff',
  PRIMARY KEY (`id_user`),
  INDEX `fk_ban_list_all_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_ban_list_all_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `xakaton`.`all_users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`staff` (
  `id_staff` INT NOT NULL,
  `count` INT NOT NULL,
  `pound` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_staff`),
  UNIQUE INDEX `id_staff_UNIQUE` (`id_staff` ASC) VISIBLE,
  INDEX `fk_staff_all_users1_idx` (`id_staff` ASC) VISIBLE,
  CONSTRAINT `fk_staff_all_users1`
    FOREIGN KEY (`id_staff`)
    REFERENCES `xakaton`.`all_users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`fws`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`fws` (
  `id_staff` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fio` VARCHAR(90) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `fio_leader` VARCHAR(90) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `rate` VARCHAR(45) NOT NULL,
  `full_expectations` LONGTEXT NOT NULL,
  `college_revue` LONGTEXT NOT NULL,
  `college_intimate` LONGTEXT NOT NULL,
  `college_other` LONGTEXT NOT NULL,
  `duties` MEDIUMTEXT NOT NULL,
  `leader_task` VARCHAR(45) NOT NULL,
  `leader_task_solve` VARCHAR(45) NOT NULL,
  `tasks_hard` VARCHAR(45) NOT NULL,
  `address_colleagues_questions` VARCHAR(45) NOT NULL,
  `address_leader_questions` VARCHAR(45) NOT NULL,
  `helping_questions` VARCHAR(45) NOT NULL,
  `leader_feedback` VARCHAR(45) NOT NULL,
  `process_tutor` VARCHAR(45) NOT NULL,
  `launch` VARCHAR(45) NOT NULL,
  `launch_people` VARCHAR(45) NOT NULL,
  `contact_colleagues` VARCHAR(45) NOT NULL,
  `sick` VARCHAR(45) NOT NULL,
  `income` VARCHAR(45) NOT NULL,
  `holiday` VARCHAR(45) NOT NULL,
  `structure_company` VARCHAR(45) NOT NULL,
  `operations_divisions` VARCHAR(45) NOT NULL,
  `covering_divisions` VARCHAR(45) NOT NULL,
  `subordinate_institutions` VARCHAR(45) NOT NULL,
  `working_comfort` VARCHAR(45) NOT NULL,
  `comfort` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_staff`),
  INDEX `fk_fws_staff1_idx` (`id_staff` ASC) VISIBLE,
  CONSTRAINT `fk_fws_staff1`
    FOREIGN KEY (`id_staff`)
    REFERENCES `xakaton`.`staff` (`id_staff`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`hr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`hr` (
  `id_hr` INT NOT NULL,
  PRIMARY KEY (`id_hr`),
  UNIQUE INDEX `id_hr_UNIQUE` (`id_hr` ASC) VISIBLE,
  CONSTRAINT `fk_hr_all_users`
    FOREIGN KEY (`id_hr`)
    REFERENCES `xakaton`.`all_users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`message_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`message_chat` (
  `id_message` INT UNSIGNED NOT NULL,
  `text` VARCHAR(250) NOT NULL,
  `request_message` TINYINT NOT NULL DEFAULT '0',
  `id_user` VARCHAR(200) NOT NULL,
  `chat_id` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_message`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`quest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`quest` (
  `id_quest` INT NOT NULL,
  `one` LONGTEXT NOT NULL,
  `two` LONGTEXT NOT NULL,
  `three` LONGTEXT NOT NULL,
  `four` LONGTEXT NOT NULL,
  `five` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_quest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`request_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`request_chat` (
  `id_request` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(250) NOT NULL,
  `id_message` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_request`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`slides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`slides` (
  `idslides` INT NOT NULL,
  `file_id` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`idslides`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `xakaton`.`tws`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xakaton`.`tws` (
  `id_staff` INT NOT NULL,
  PRIMARY KEY (`id_staff`),
  CONSTRAINT `fk_tws_staff1`
    FOREIGN KEY (`id_staff`)
    REFERENCES `xakaton`.`staff` (`id_staff`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
